project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: "Copyright 2022, Carly Neilson"
    right:
      - icon: github
        href: https://github.com/carlyneilson
  title: "mysite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis walk through.qmd
      - mywork.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



