project:
  type: website
  output-dir: docs

website:
  page-footer:
    left: "Copyright 2022, Carly Neilson"
    right:
      - icon: github
        href: https://github.com/carlyneilson
  title: "Carly's Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis walk through.qmd
      - mywork.qmd
      - href: https://drive.google.com/file/d/151qo6aYI4JgiBVJDd9_rQqhx2fe8u5RN/view?usp=sharing
        text: Resume
      - paper.qmd
      - newsstory.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



