---
title: "News Story"
editor: visual
---

# **Hate Crimes in the District in 2021**

## *Written for Advanced News Writing Class*

### By Carly Neilson

In Cathedral Heights: A gay, Asian American man was on a walk with his parents when a white man yelled racial slurs at them and pushed his elderly parents. In Northeast: A Black transgender woman was beaten and stabbed by three people in a laundromat after being verbally assaulted with homophobic slurs. In NOMA: An Asian American jewelry store owner was attacked by a white customer in his own store resulting in 14 stitches on his face as slurs were hurled at him.

These are just three of the 119 hate crimes that occurred across Washington D.C. this year, which have been on the rise over the past five years, according to D.C. Police Department data. Experts attribute the rise in hate crimes in the District to increased reporting to police and polarizing political events.

Since 2016 reported hate crimes to D.C. police increased 140% compared to the previous five year period. The most common offenses include simple assault, threats and destruction of property.

The majority of victims were targeted for their sexual orientation, followed closely in more recent years by victims' ethnicity/national origin and race. Black, Jewish and Hispanic victims were the most targeted in that five year period. Hate crimes against Asian Americans doubled from 2020 to 2021.

"In the past few years, everything that has happened in this country has combined together to make it so a place like the District, which is a huge melting pot, allows people that have hate bias motivations within them to act and for it to become a breeding ground here," Sgt. Nicole Brown, who oversees hate crimes at that D.C. Police Department, said.

Brown said more victims have come forward recently to report hate crimes to police than in past years, accounting for this increase. Political events and a diverse population in the District have contributed as well to the increase in hate crimes over the past five years, she said.

In D.C. the number of reported hate crimes decreased slightly in 2020. However, hate crimes in Maryland rose 110%, according to FBI data. Nationwide reported hate crimes reached the highest level in 12 years.

Brown said the rise in hate crimes last year in Maryland and Virginia, yet a decrease in D.C. can be attributed to the pandemic. She said with the city's large transient population, residents in surrounding states were not coming into the District due to business closures. So, hate crimes against minority residents were more likely to occur in their home states.

"With COVID-19 a lot of the restaurants and bars were closed, especially in the earlier part of the year, so a lot of people were staying home in Maryland and Virginia," Brown said. "That has a lot to do with the number shift."

She said it is hard to change people's biased and hateful views, however, by continuing to report hate crimes police can show D.C. residents they take the issue seriously. This will prevent potential perpetrators from acting on their biases if they know the serious consequences of committing a hate crime in D.C., she said. If convicted, offenders can face up to 1-and-a-half the maximum fine or prison sentence for the underlying crime. 

"The more we get out there and show we take this seriously that D.C. is a jurisdiction where if a victim perceives that they were a target of a particular crime, based on a protected trait, we check the hate crime box," Brown said. "We want to let people know that hate crimes are serious and we do not want them here."

Arusha Gordon, who works with hate crime victims at the Lawyers Committee for Civil Rights Under Law, said increases in hate crimes targeting specific groups reflect political and social events. For example, the rise in crimes against Asian Americans came during the pandemic due to discourse about where the coronavirus originated. She said an increase in crimes against African Americans followed the racial justice movements in 2020, as those who are not supportive of racial justice were fueled to act.

"Those who are most vulnerable are members of historically marginalized communities," Gordon said. "I would flag that people who exist at the intersection of more than one, historically marginalized identity might be particularly vulnerable to hateful activity."

She said in order to decrease hate crimes, communities need to address "the root of the problem." Work needs to be done with youth to learn about biases and to increase restorative justice programs, Gordon said.

"Rather than just locking people up who've engaged in hateful activity, we should really be thinking about if there is an alternative that addresses the problem?" Gordon said.

Meredith Weisel, the deputy director of the Anti-Defamation League's Washington D.C. office which aims to end anti-semitism and bigotry, said hate crimes have a "lasting and immeasurable impact" on the victim and their community. She said even nonviolent crimes like graffiti of a swastika, can have a large impact.

"Behind every hate crime statistic, there's a person, family and community who are dealing with unimaginable things as somebody was specifically targeted for a protected immutable characteristic like race, religion, national origin, sexual orientation, sex, gender identity or disability," Weisel said.

She said since 2016, from "Charlottesville to Capitol Hill", leaders have been more divisive. Leaders need to condemn acts of hate, as being polarizing will only spur people to act on their biases \-- which accounts for this rise in hate crimes, Weisel said. 

"That has contributed to a climate where people feel emboldened, and energized to act \[on hateful biases\]," Wiesel said. "We really feel it's so important that our leaders are condemning things like anti-semitism and hate whenever it occurs."

She said the solution to decrease hate crimes is for police to prioritize reporting while gaining trust in their community to allow more victims to come forward. She said communities need to expand anti-hate education and victim services programs like restorative justice.

"We have to ensure that combating hate crimes is a top priority," Weisel said. "That is a form of justice."
