---
title: "English Paper"
editor: visual
---

# **Close Reading of "Her Kind" by Anne Sexton**

## *Written for American Poetry II Class*

I wrote an analysis of the confessional style poem titled "Her Kind" for my American poetry class. In this paper I discuss the different rhetorical strategies that the poet Anne Sexton uses to convey the message of her poem. One of the main devices she uses is extended metaphor. She uses the extended metaphor of a witch to push a feminist and individualist theme in the poem. Sexton also uses rhyme scheme, narrative story, imagery, and alliteration among other devices to tell the story of a woman enjoying her chosen freedom.

### By Carly Neilson

"Her Kind" by Anne Sexton tells the story of a woman living contently outside of society through a rigid rhyming structure coupled with a feminist theme. The poem's more traditional aspects include alliteration, repetition of lines, and consonance. The most striking image in this poem is the extended metaphor of the witch the narrator puts into scenarios to highlight the freedom of being a different kind of woman -- one who enjoys solitude. This poem follows a strict rhyme scheme and uses a witch as a feminist symbol to show readers that there is power and happiness in a woman's individuality. 

"Her Kind" is composed of three stanzas of exactly seven lines. Each stanza in the poem follows an ABABCBC rhyming scheme, with the exception of the second stanza being ABABCAC. The second to last lines in each stanza begins with "a woman like that is." The final line in each stanza reads the same: "I have been her kind." The repetition of that line ties into the title of the poem. These strict, repeated structures give the poem rhythm and to reinforce the feminist theme -- happiness or rejection of traditional society in solitude. This theme is emphasized with each stanza showing the "witch" in a different scene. Yet the repetition of the lines at the end of the stanzas highlights the witch is an untraditional type of woman that the narrator has been as well. 

Sexton utilizes alliteration and consonance to her advantage when creating the poem's rhythm. Some examples of alliteration are on line two reading "black air, braver" and on line nineteen "where your wheels wind." She uses consonance to compliment the imagery of the witch's world in the poem. A stellar example of this is in the second stanza when Sexton lists items in the witch's cave: "skillets, carvings, shelves, closets, silks, innumerable goods." The repetition of plural objects or "s" sounds here not only create sound in the poem but help to display an image to the reader of the witch's dwelling. Some other examples of consonance appear on line fifteen with "your cart, driver" and line seventeen with "last bright routes."

The theme of "Her Kind" is curated through Sexton's use of imagery, symbols, and narrative story. The narrator in this poem is telling the story of a woman who lives outside of society yet is content. She introduces the symbol of a witch in the very first line of the poem to describe this woman. Sexton writes in the first person point of view to articulate that the narrator herself is like the witch. She places emphasis on this through the repeated line "I have been her kind." Each stanza shows the reader a different vignette into this witch's life, giving the poem a narrative structure. The second to last lines in each stanza summarizes the themes of each story within them. Her striking imagery comes within each stanza to tell the story of the witch and narrator. 

The first stanza describes the witch's haunting of society. Sexton writes that this narrator has "gone out, a possed witch, haunting the black air . . . dreaming evil." These first few lines do a lot in terms of introducing the character. Sexton continues to highlight her peculiarity with images like "twelve-fingered." Even on line six writing "a woman like that is not a woman, quite" to further underline her oddities.

The second stanza describes the woman's comfort in isolation. Sexton explains how the narrator sheltered herself in a cave, yet is comfortable with all the things she collects to make it a home and how she helps others, like "the worms and the elves." This stanza's story is reminiscent of a traditional fairytale-like witch that readers may be familiar with. Line thirteen highlights how the woman is "misunderstood" meaning most don't realize the beauty or happiness that this living style brings the witch.

The third and final stanza is an ode to the witch's demise. Sexton alludes that the witch is being burned at the stake with vivid images like "where your flames still bite my thigh and my ribs crack where your wheels wind." On line twenty she writes "a woman like that is not ashamed to die" which hones in the theme that despite going against conventional society, the witch was content with her life even if it leads to her death.

The independence of the witch and her proud rejection of traditional society lends to a feminist tone of the poem. Most of the imagery in this poem tells a story of a woman's power. Lines like "braver at night" show the will of this woman's actions, however, the most powerful lines here come when the narrator compares herself to this witch. This poem is purely feminist due to the theme that the witch is content living against what society tells her to do. The narrator is unashamed to say that she has "been her kind." Poets earlier in American literature wrote in a similar style to Sexton, yet the content of their poems rarely tackled topics below the surface. Anne Sexton's work as a whole proves that poetry can follow traditional rhyme schemes or styles yet still tackle deeper topics like feminism.
